[
    {
        "type": "rainbow",
        "fileName": "day.svg",
        "backgroundColor": "#ffffff",
        "foregroundColor": "#0f172a",
        "strongColor": "rgb(124,58,237)",
        "weakColor": "#94a3b8",
        "radarColor": "rgb(124,58,237)",
        "growingAnimation": true,
        "saturation": "85%",
        "contribLightness": [
            "30%",
            "40%",
            "50%",
            "60%",
            "70%"
        ],
        "duration": "20s",
        "hueRatio": -18
    },
    {
        "type": "rainbow",
        "fileName": "night.svg",
        "backgroundColor": "#020617",
        "foregroundColor": "#f1f5f9",
        "strongColor": "rgb(0,229,255)",
        "weakColor": "#475569",
        "radarColor": "rgb(0,229,255)",
        "growingAnimation": true,
        "saturation": "90%",
        "contribLightness": [
            "25%",
            "35%",
            "45%",
            "55%",
            "65%"
        ],
        "duration": "20s",
        "hueRatio": -18
    }
]
